# Generated by Django 5.0.4 on 2024-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
