# Generated by Django 5.0.4 on 2024-05-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0003_posteo_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria'),
        ),
    ]
