# Generated by Django 5.0.4 on 2024-05-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercambio',
            old_name='user2',
            new_name='user_2',
        ),
    ]
